### ISSUE TITLE
Real Estate Pro Theme

### ISSUE THREAD

**Issue by livingwandsworth** [Markup360/realestatepro#11]
Hello there!
I've got one question. I have watched your tutorial videos on youtube. I have specifically watched the first 2 parts and followed every step. When I visit the site though, it doesnt give me the theme in the way it should be. I have attached a picture of what comes up when it loads. Could you please help me in this and tell me what to do in order to fix it?

Thank you very much!

Andreas Michael

-Originally asked by icybravo on 31-10-2016, 08:40 PM, migrated from site forum

**Comment by Markup360** [comment]
Hi Michael,

From the Admin go to Appearance>Widgets>and remove the widgets from the the top sidebar.
