### ISSUE TITLE
Home Page View

### ISSUE THREAD

**Issue by livingwandsworth** [Markup360/realestatepro#12]
Hi Naz,

I installed the real estate pro template on my site happyhomesph.com and I follow the video 2 instruction https://www.youtube.com/watch?v=ABpNYjIvdvk. In the video, when the Home page was created and published the "Search Properties", "Latest Properties for sale", and the "Latest Properties for Rent" was automatically created in the Home page. But in case, upon following exactly the instruction in the video, my Home page is still blank. 

This is a live website hosted by HostGator. Please help. Thanks in advance.

Regards,
Herbin 

-Originally asked by Herbin on 13-07-2016, 10:41 AM, migrated from site forum

**Comment by Markup360** [comment]
Hello Herbin,

Under Settings>Reading did you set the Front Page to be the Home page?

**Comment by livingwandsworth** [comment]
Yes Naz, I set it to Home page.

**Comment by Markup360** [comment]
Can you confirm that you installed RealEstatePro and not Graviton, do you see the Properties on the left in the admin?

**Comment by livingwandsworth** [comment]
Hi Naz,

I installed RealEstatePro Template and yes u can see the Proties in the left pane.

**Comment by Markup360** [comment]
Are you able you able to give me access and I will take a look?

**Comment by Markup360** [comment]
Sorry I just realised you are watching a video for the old version of RealEstatePro, what you need to do is on the Home page, on the right hand side under Page Template choose Front Page.

**Comment by livingwandsworth** [comment]
Hi Naz,

Thank you very much. It works!!!.
