### ISSUE TITLE
Question about side bar 

### ISSUE THREAD

**Issue by headgood17** [Markup360/realestatepro#17]
How can I change the size of side bar? I want to make the property search form in the side bar become as normal as the video demo shown, but now the width of my property search form in the side bar is a little bit small.
![image](https://cloud.githubusercontent.com/assets/26901526/24825014/a6b0185c-1c48-11e7-8fd4-df5226c048d3.png)

**Comment by Markup360** [comment]
You have added the wrong widget to the search bar, the correct one you need is 

> RealEstatePro - Property Search Form - Siderbar

you appear to have used

>RealEstatePro - Property Search Form - Pages

which is for when you want to add the form to a page rather than the side bar.
