### ISSUE TITLE
How to collect Email-Id and send an attachment in the email immediately, to visitor?

### ISSUE THREAD

**Issue by Hom177** [Markup360/realestatepro#19]
From a Website using RealEstatePro Theme, how to collect Email-Id from Visitor and send an attachment in the email immediately to Visitor? Let's assume, that Visitor clicked on a Menu Link on the Page.

**Comment by Markup360** [comment]
You can use the contact page template or contact page layout to do this, ensure you set a unique e-mail subject, then use your e-mail application to create a rule to send back an attachment based on the subject line.

**Comment by Hom177** [comment]
Can you please do a video, showing it step by step? Please.
Thanks.

**Comment by Markup360** [comment]
I think it would be a while before I do this type of video because it is more about e-mail than WordPress.
