### ISSUE TITLE
Additional Functionality Compatible with Theme

### ISSUE THREAD

**Issue by livingwandsworth** [Markup360/realestatepro#2]
I am following videos to create an real estate website and i am pretty much happy with the website i end up with.
However, i am looking for any inbuilt functionality(if available) in theme or markup360 plugin compatible with theme.
User Log in/Registration
Post an Ad(Customer posting an Ad)
Embedding Video into pages.

**Comment by Markup360** [comment]
When you say posting and ad do you mean adding a property or ad as in advertisement?

**Comment by livingwandsworth** [comment]
Yes..

**Comment by Markup360** [comment]
Yes to which one? Property or Advert?
