### ISSUE TITLE
Are the Contacts entered in the Contacts Page, saved in My SQL Database?

### ISSUE THREAD

**Issue by Hom177** [Markup360/realestatepro#20]
In the Contacts Page using RealEstatePro Theme, when Visitor enters their Contact information and clicks on the Contact Us button, what happens? Is the information stored in the My SQL Database? How to retrieve it?

**Comment by Markup360** [comment]
If you have added your e-mail to the contact page/template you will receive the e-mail, the contact details are not stored in the database, though you can get plugins that store contacts.

**Comment by Hom177** [comment]
Can you please suggest some good, free plugins to store the Contacts in the My SQL Database? Maybe even any videos that show how to use them as well.
Thanks.

**Comment by Markup360** [comment]
I haven't used any in the past but try something like;

https://wordpress.org/plugins/contact-form-advanced-database/
