### ISSUE TITLE
Home page slider stuck on the temporary image

### ISSUE THREAD

**Issue by iamforliberty** [Markup360/realestatepro#22]
I successfully installed but home page slider stuck on the temporary image. please see www.mylibertyhome.co.ke

Previously slider was working until I used the page builder on the home page. It still works on the other pages like properties and sales. Please help

**Comment by Markup360** [comment]
1. Have you added your own images to the slider, the one created with the page builder needs to be edited on page, it is not connected to the slideshow. Or you should change the page template to Front Page.

2. In your side bar you have added the wrong search form, you should be using the widget

>RealEstatePro - Property Search Form - Sidebar

3. The property search results page template should be the 'Default Template' you have changed it to Front Page which will not work,
