### ISSUE TITLE
Nivo slider

### ISSUE THREAD

**Issue by headgood17** [Markup360/realestatepro#23]
I want to make the home page nivo slider to show the dot or number options, except for only arrow option. How to do that?

**Comment by Markup360** [comment]
By default they are hidden because they are generally unusable on mobile devices, too small, but if you want to display them you can. You need to edit open one of the following file depending on whether you are using the default full width front page or boxed width.

> your_installation/realestatepro/layouts/full-width.php
> your_installation/realestatepro/layouts/boxed-width.php

You will then find this code block at the start of the file;

```
(function($){

    jQuery(document).ready(function($) {
    $('#slider').nivoSlider({
     effect:'<?php echo get_theme_mod( 'realestatepro_nivo_slider_effect', esc_attr__( 'fade', 'graviton' ) ) ?>',
     slices: 5,
     animSpeed: 500,
     pauseTime: 5000,
     captionOpacity: 0.5,
     controlNav: false,
     directionNav: true,
     pauseonhover: true});
});

})(this.jQuery);

```
You simply need to change 

`     controlNav: false,`

to

`     controlNav: false,`

However, you should use a child theme to do this otherwise if you update RealEstatePro the change will be overwritten.

**Comment by headgood17** [comment]
When I reached "your_installation/realestatepro/layouts", I couldn't find "full-width.php" or "boxed-width.php", but I could find a lot of sub-folders such as "realestatepro-layouts", "property-search-results", "confirmation". Then I opened them one bye one, but still couldn't find the suitable .php. Where can I find the "full-width.php" or "boxed-width.php"?

**Comment by Markup360** [comment]
My error, sorry about that it should be


>your_installation/realestatepro/layouts/front-page/full-width.php

or


>your_installation/realestatepro/layouts/front-page/boxed-width.php

**Comment by headgood17** [comment]
After the change of code, where do I need to upload to? The child theme or the parent theme? I uploaded it to the child theme: the whole subfolder front-page.zip and then unzip it in the child theme, but there is no change in the webpage.

**Comment by headgood17** [comment]
I have done that already. I can find the dot but if I want the number 1,2,3... any other way?

**Comment by Markup360** [comment]
For it to work in the child theme you must copy from the parent theme the folder `Layouts`, and in it should be the folder `Front-Page` with the `full-width.php` ammended file. You must also copy the `template-front-page.php` from the parent theme to the root of the child theme.

I'm not sure how to get the numbers, can you start a new thread for that.
