### ISSUE TITLE
Add Property problem

### ISSUE THREAD

**Issue by SaracenMerchants** [Markup360/realestatepro#24]
Hi Nazim,

First, I'd just like to thank you for providing us with a free template. I have enjoyed using it and found your tutorial on youtube very easy to follow. The issue I am having concerns the Properties section. Up until last night everything was fine, I was able to "Add Property" and input property data without any problems, then, without warning, my normal "Property Details" box changed. 

It went from a full, easy to use box editor to a blank window that now just displays code (please see picture.) 
<img width="1017" alt="screen shot 2017-04-24 at 07 06 05" src="https://cloud.githubusercontent.com/assets/20611096/25323082/fa7dc8fa-28bc-11e7-9a1f-c0ab60f62120.png">

Now when I look at all the other property listings I have already uploaded the "Property Details" box has also changed as well as the "Amenities" box.

Please help me, as this has become quite frustrating.

Thank you

**Comment by Markup360** [comment]
Hello,

Can you post a screenshot of the whole Properties section?

**Comment by SaracenMerchants** [comment]
Weirdly enough, it appears as if everything has returned to normal. I haven't touched anything so I have no idea what could have happened. 

<img width="1291" alt="screen shot 2017-04-24 at 14 16 23" src="https://cloud.githubusercontent.com/assets/20611096/25336643/b8300d00-28f8-11e7-9c25-a58c19d88b6f.png">

**Comment by Markup360** [comment]
Great, if it happens again you can re-open this issue.

**Comment by SaracenMerchants** [comment]
No problem. Thanks again :)
