### ISSUE TITLE
Latest properties for Sale

### ISSUE THREAD

**Issue by livingwandsworth** [Markup360/realestatepro#3]
Hi Naz,

I am looking to have a page that would have a Latest properties for sale, so a page or multiple pages that just showcases as in the HOME page. so a client does not have to search, they can just browse.

Is it possible to build, Ideally I am looking to place it on the Property Search page i have.

Here is our site so far. http://levante-rc.com

Many thanks

Jeff 

-Originally asked by jeffscott20 on 22-11-2016, 11:35 AM, migrated from site forum

**Comment by Markup360** [comment]
Hi Jeff,

It is possible. You need to add a Post Loop widget using the Page Builder that gets the properties for sale and sorts them by sale date, you will need to select either the Content Listing Card or Wide to display the properties.

**Comment by livingwandsworth** [comment]
Naz

Perfect I will give it a go
------------------------------------
Naz, perfect it worked.......thanks for the guidance.
