### ISSUE TITLE
RealEstatePro Demo

### ISSUE THREAD

**Issue by livingwandsworth** [Markup360/realestatepro#4]
I have successfully installed the Graviton theme and its sample data and am very pleased with it.  Smile

However, if I replace Graviton with the RealEstatePro theme, the site content and format do not change. Would you expect this and is sample data included with the RealEstatePro theme?

Alternatively should I install the RealEstatePro theme to a clean installation of WordPress and an empty MySQL database?

-Originally asked by nemo on 20-05-2016, 05:41 PM, migrated from site forum

**Comment by Markup360** [comment]
Yes, I would expect this. The way to know if RealEstatePro has installed correctly is if you see Properties, Slideshow and Featured Properties on the left had menu. Rember Graviton is a framwork so all our templates will have the same look when activated so you become familiar and proficient.
There isn't any sample data with RealEstatePro.
