### ISSUE TITLE
Changing Currency Problems

### ISSUE THREAD

**Issue by livingwandsworth** [Markup360/realestatepro#5]
Hi,
I am using a child theme of the Real Estate Pro template and I cannot change the currency options. The "Save" option is greyed out when using it as a child theme. How can I change the currency from dollars to GBP for my child theme?
Thank you. 

-Originally asked by chrisoliver1990 on 25-06-2016, 05:16 PM, migrated from site forum

**Comment by Markup360** [comment]
Hi,

If you change other options in the customizer is the Save button still greyed out or only for the currency?
Also what changes have you made to the child theme specifically any coding changes.

**Comment by livingwandsworth** [comment]
If I change a few settings such a background color etc, I then go back to change the currency and the Save & publish button becomes active. When I save it however the settings are not saved. It reverts back to the dollar.

**Comment by Markup360** [comment]
What if you revert back to the parent theme then change it?

**Comment by livingwandsworth** [comment]
I tried that various times. It saves as GBP £ on the parent theme fine but as soon as I apply the child theme it reverts back to dollars.
I've had to use JavaScript replace to replace all instances of dollar with pound. It's really not an ideal solution but the only one I could find. It is the only child theme that does not allow me to save the options.
Thanks,
Chris
