### ISSUE TITLE
Featured Images for Properties

### ISSUE THREAD

**Issue by livingwandsworth** [Markup360/realestatepro#6]
Thank you for approving my account!

I'm looking forward to using Real Estate Pro on a new website and will purchase the support plan if I do, but have encountered a couple issues preventing me from launching the site.

Most importantly, it appears there are no Featured Images for the Properties post type. This results in no photos being displayed on the Properties Archives listing page. (See Screenshot) And, I can therefore not include Properties in the SiteOrigin Post Carousel widget since only a black box appears where the feature image should be.

Is there any way to list Properties with a featured image using the Page Builder or a widget?

Thanks in advance for any feedback.

-Originally asked by agreda on 10-07-2016, 01:53 PM, migrated from site forum

**Comment by Markup360** [comment]
Hi Jim,

To create a list/cards of properties you follow these steps;

1. One the edit screen for the relevant properties give them a Tag, e.g. Featured/Luxury/Promoted.
2. One the page that would like these properties to appear on using the Page Builder add the Post Loop widget and click edit to start building the loop.
3. Under Template choose either content-listings-cards.php or content-listings-wide.php.
4. Click Build Posts Query, set Post type to Properties, and under Taxonomies, type in your tag, it should auto suggest it. Set any other options.
5. Click Save Query, then Done, then publish/update the page.

**Comment by livingwandsworth** [comment]
Thank you! I'll give that a go...
