### ISSUE TITLE
Contact Form Widget Not Working

### ISSUE THREAD

**Issue by livingwandsworth** [Markup360/realestatepro#8]
I have spent hours trying to get emails to consistently send from the SiteBuilder Contact Form Widget. 

I could only get it to work two times, IF the send-to email matched that of the primary WP Admin email AND if the Akismet setting was set to flag message subject rather than return error. But after updating to the new theme version, now that is no longer working.

I even installed an SMTP plugin, and was able to send one more message successfully, but never again since, after multiple attempts.

FYI: Upon submission of the SiteBuilder contact form, the page does refresh with the confirmation message, but no emails are sent. And no, they are not being trapped by any spam filters. I confirmed using various email accounts (outlook, gmail and email client). There is nothing in the error logs.

Installation of the JetPack Contact Form/Feedback module confirms that there is no issue with the site sending emails from forms. That works fine. However, the JetPack form shortcode does not work within the Page Builder content. It does work in the sidebar widget, and in a post by itself, but I need it to work inside a Text or SiteBuilder widget on a page built using the page builder...FYI: the JP form renders, but nothing upon submit.

Any suggestions?

Ideally I'd like to get the JetPack shortcode working since that consistently sends the email, and adds the contact to the JP Feedback management area, but nothing happens when you click the Submit button.

Thanks in advance for any help! 

-Originally asked by agreda on 25-07-2016, 11:18 PM, migrated from site forum

**Comment by Markup360** [comment]
Is the contact form on your site the one with issues on the right hand side the one with the issues?

**Comment by livingwandsworth** [comment]
Thanks for asking Naz. Both - Neither the sidebar widget, nor the widget within the Page Builder content at http://paulvickersrealty.com/contact are forwarding emails.

The only way I can get Contact emails to forward is by using the JetPack Feedback form shortcode. But that will not wotk withing the Page Builder, only in the sidebar or in a post/page using the WP editor. Any way we could get JP shortcodes to play nice within the Page Builder?

**Comment by Markup360** [comment]
I would recommend giving Ninja Forms a go, that seems to play nice with the Page Builder plugin.

https://en-gb.wordpress.org/plugins/ninja-forms/

**Comment by livingwandsworth** [comment]
Thanks, Ninja Forms is working, and also has a submissions management area.

Odd how the native Page Builder contact widget work, and too bad JetPack was incompatible. But thanks again for the plugin recommendation.

**Comment by livingwandsworth** [comment]
Herbin says;

Contact form is also not working in my site. I tried contact form #7 and it works.

Regards,
Herbin
http://www.happyhomesph.com
