### ISSUE TITLE
Home page display is not as expected

### ISSUE THREAD

**Issue by livingwandsworth** [Markup360/realestatepro#9]
I am following up the youtube video https://www.youtube.com/watch?v=ABpNYjIvdvk to create a real estate website of my own. I downloaded the RealEstatePro theme and installed it, then i built Home and Blog page. After publishing my home page , most of items are missing from the page..Top header(email and phone no.) are not there. Also, search property filters are not visible..Also, page is opening with tab "page not found".

Here is the link to my website
http://westernodishaproperty.com/ 

-Originally asked by iamajaya on 10-08-2016, 01:51 AM, migrated from site forum

**Comment by Markup360** [comment]
For the top header go to Appearance>Widget>Top Banner, then move a Page Layout Builder into that and create whatever layout you want, this can be just one row then add you tel/e-mail to it.

If the Home page is missing search form, from the Home page edit screen on the right hand side under Page Template choose Front Page.

As to why your home page is not showing up, I don't know, but why is your home page /index.html ? Have you set the Home page to be the Front page from Admin?
